#!/usr/bin/env bash
# Write a Bash script that will display information about subdomains.

domain_information () {
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print "The subdomain " $2 " is a " $3 " record and points to " $4}'
}

if [ "$#" -eq 1 ]
then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]
then
  domain_information "$1" "$2"
fi
