#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
# Check if nginx services are active
service nginx start
echo "Hello World" > /var/www/html/index.nginx-debian.html
