#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i "/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "/server_name _;/ a error_page 404 /404.html;" /etc/nginx/sites-available/default

# Restart the Nginx web server to put the changes into effect
sudo service nginx restart
