#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get install haproxy -y
sudo chmod 777 /etc/default/haproxy
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy # Changed '>>'' to 'sudo tee -a', shellcheck error
sudo chmod 777 /etc/haproxy/haproxy.cfg
sudo printf "\nfrontend http_front\n\tbind *:80\n\tdefault_backend http_back\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo printf "\nbackend http_back\n\tbalance roundrobin\n\tserver web-01 34.148.132.49:80 check\n\tserver web-02 3.95.23.58:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
