#!/usr/bin/env bash
# Bash (init) script that manages manage_my_process.
file="/var/run/my_process.pid"
case "$1" in
    start) ./manage_my_process &
        echo && > $file
        echo 'manage_my_process started'
        ;;
    stop) kill "$(pgrep -f 'manage_my_process')"
        rm -f $file
        echo 'manage_my_process stopped'
        ;;
    restart) kill "$(pgrep -f 'manage_my_process')"
        rm -f $file
        ./manage_my_process &
        echo $$ > $file
        echo 'manage_my_process restarted'
        ;;
    *) echo 'Usage: manage_my_process {start|stop|restart}'
        ;;
esac
