#!/usr/bin/env bash
# Bash script that displays Best School 10 times.

str=0
while [ "$str" -le 10 ];
do
    echo 'Best School'

    if [ "$str" -eq 9 ]
    then
        echo 'Hi'
    fi
    str=$((str+1))
done
