#!/usr/bin/env bash
# SSH client configuration
# Your SSH client configuration must be configured to use the private key ~/.ssh/school
# Your SSH client configuration must be configured to refuse to authenticate using a password

Host ubuntu
  passwordAuthentication no
  IdentityFile ~/.ssh/school
